version: '3.7'
services:
  server:
    build:
      context: spring-social
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring-social
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - backend
      - frontend
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0.25
    restart: always
    environment:
      - MYSQL_DATABASE=spring-social
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend

  app-client:
    build:
      context: react-social
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:3000/
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - server
    networks:
      - frontend

volumes:
  my-db:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge