@startuml
component Vision [
<<Vision>>

Be the most used app
working as a grocery
reminder
]

component Mission [
<<Mission>>

Provide a grocery
list platform, so
nobody will forget
the things they need
to buy next time they
go shopping
]

component Goal [
<<Goal>>

To have an app with
small rate-failure
]

component Strategy [
<<Strategy>>

Have the tools up and
running all the time
]

component Objective [
<<Objective>>

By January 1, 2021,
<1% failure rate
]

component Tactic [
<<Tactic>>

Use the latest updates
and technologies
]

component BusinessRule [
<<BusinessRule>>

Platform available
only on a small city
]

component LoginBusinessRule [
<<BusinessRule>>

Login functionality must
be processed within 1 second
]

component GroceryListBusinessRule [
<<BusinessRule>>

Items in the grocery list
cannot be modified,
only added or removed
]

component ExternalInfluencer [
<<ExternalInfluencer>>

Economic recession
--
Category: Environment
]

component Assessment [
<<Assessment>>

Economic recession
causes decline in
shopping, therefore,
app is no longer used
--
Category: threat
]

component BusinessPolicy [
<<BusinessPolicy>>

No old technologies
and no bugs
]

[Mission] -left..> [Vision] : <<MakesOperative>>
[Goal] -up..> [Vision] : <<Amplifies>>
[Strategy] -left..> [Goal] : <<ChannelsEffortsTowards>>
[Objective] -up..> [Goal] : <<Quantifies>>
[Tactic] -left..> [Objective] : <<ChannelsEffortsTowards>>
[Tactic] -up..> [Strategy] : <<Implements>>
[BusinessRule] -up..> [Objective] : <<SupportsAchievementOf>>
[LoginBusinessRule] -up..> [Objective] : <<SupportsAchievementOf>>
[GroceryListBusinessRule] -up..> [Objective] : <<SupportsAchievementOf>>
[Assessment] -left..> [ExternalInfluencer] : <<judge>>

@enduml